eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      default-zone: http://localhost:8761/eureka/
server:
  port: 8775
spring:
  application:
    name: service-hi